[mypy]
python_version = 3.12
strict = false
ignore_missing_imports = true
disallow_untyped_defs = true
warn_return_any = false

[mypy-weasyprint.*]
ignore_missing_imports = true
[mypy-jose.*]
ignore_missing_imports = true
